In [2]:
import pandas as pd

In [11]:
df = pd.read_csv("data/17.3 bank-full.csv", sep=",", index_col="id")
print(df.shape)
df

(45211, 17)

,age,job,marital,education,balance,housing,loan,default,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
id,,,,,,,,,,,,,,,,,
0,58,management,married,tertiary,2143,yes,no,no,unknown,5,may,261,1,-1,0,unknown,no
1,44,technician,single,secondary,29,yes,no,no,unknown,5,may,151,1,-1,0,unknown,no
2,33,entrepreneur,married,secondary,2,yes,yes,no,unknown,5,may,76,1,-1,0,unknown,no
3,47,blue-collar,married,unknown,1506,yes,no,no,unknown,5,may,92,1,-1,0,unknown,no
4,33,unknown,single,unknown,1,no,no,no,unknown,5,may,198,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45206,51,technician,married,tertiary,825,no,no,no,cellular,17,nov,977,3,-1,0,unknown,yes
45207,71,retired,divorced,primary,1729,no,no,no,cellular,17,nov,456,2,-1,0,unknown,yes
45208,72,retired,married,secondary,5715,no,no,no,cellular,17,nov,1127,5,184,3,success,yes
45209,57,blue-collar,married,secondary,668,no,no,no,telephone,17,nov,508,4,-1,0,unknown,no
45210,37,entrepreneur,married,secondary,2971,no,no,no,cellular,17,nov,361,2,188,11,other,no

In [14]:
df.marital.values.tolist()

['married',
 'single',
 'married',
 'married',
 'single',
 'married',
 'single',
 'divorced',
 'married',
 'single',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'single',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'single',
 'married',
 'divorced',
 'married',
 'single',
 'single',
 'single',
 'single',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'divorced',
 'single',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'single',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'single',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'divorced',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'single',
 'married',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'married',
 'single',
 'single',
 'divorced',
 'married',
 'married',
 'single',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'divorced',
 'single',
 'single',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'single',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'divorced',
 'married',
 'single',
 'married',
 'single',
 'single',
 'single',
 'divorced',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'single',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'single',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'divorced',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'single',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'divorced',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'divorced',
 'divorced',
 'married',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'married',
 'married',
 'single',
 'single',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'single',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'divorced',
 'married',
 'divorced',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'single',
 'married',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'divorced',
 'divorced',
 'married',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'single',
 'single',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'single',
 'divorced',
 'single',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'divorced',
 'single',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'divorced',
 'married',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'married',
 'divorced',
 'divorced',
 'married',
 'single',
 'married',
 'single',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'single',
 'divorced',
 'single',
 'single',
 'divorced',
 'married',
 'married',
 'single',
 'married',
 'divorced',
 'single',
 'married',
 'married',
 'single',
 'divorced',
 'single',
 'married',
 'married',
 'single',
 'divorced',
 'single',
 'married',
 'single',
 'divorced',
 'married',
 'single',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'single',
 'single',
 'married',
 'married',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'divorced',
 'single',
 'married',
 'single',
 'divorced',
 'divorced',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'single',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'divorced',
 'married',
 'single',
 'single',
 'single',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'divorced',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'divorced',
 'married',
 'married',
 'married',
 'married',
 'single',
 'married',
 'single',
 'single',
 'married',
 'married',
 'single',
 'divorced',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'single',
 'divorced',
 'married',
 'single',
 'married',
 'married',
 'married',
 'married',
 'married',
 'married',
 'single',
 ...]

In [17]:
df.marital.unique()

array(['married', 'single', 'divorced'], dtype=object)

In [19]:
df.age.unique()

array([58, 44, 33, 47, 35, 28, 42, 43, 41, 29, 53, 57, 51, 45, 60, 56, 32,
       25, 40, 39, 52, 46, 36, 49, 59, 37, 50, 54, 55, 48, 24, 38, 31, 30,
       27, 34, 23, 26, 61, 22, 21, 20, 66, 62, 83, 75, 67, 70, 65, 68, 64,
       69, 72, 71, 19, 76, 85, 63, 90, 82, 73, 74, 78, 80, 94, 79, 77, 86,
       95, 81, 18, 89, 84, 87, 92, 93, 88], dtype=int64)

In [21]:
df.age.nunique()

77

In [23]:
df.age.describe()

count    45211.000000
mean        40.936210
std         10.618762
min         18.000000
25%         33.000000
50%         39.000000
75%         48.000000
max         95.000000
Name: age, dtype: float64

In [27]:
df.balance.describe()

count     45211.000000
mean       1362.272058
std        3044.765829
min       -8019.000000
25%          72.000000
50%         448.000000
75%        1428.000000
max      102127.000000
Name: balance, dtype: float64

In [32]:
df.loan.unique()

array(['no', 'yes'], dtype=object)